name: Process Data and Build Docker Image

on:
  schedule:
    - cron: '0 5 * * *' # Runs every day at 5 AM UTC
  push:
    branches:
      - main # Also run on pushes to main branch for testing
  workflow_dispatch: # Allows manual triggering

jobs:
  # ===================================================================
  # JOB 1: Process Reddit data and update the recommendations database
  # ===================================================================
  build-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create data directory
        run: mkdir -p ./data

      - name: Cache and Download IMDb Datasets
        uses: actions/cache@v4
        id: cache-imdb
        with:
          path: ./data/*.tsv.gz
          key: ${{ runner.os }}-imdb-data-v1
      
      - name: Download IMDb Datasets if not cached
        if: steps.cache-imdb.outputs.cache-hit != 'true'
        run: |
          echo "Cache not found, downloading IMDb data..."
          wget -q -O ./data/title.basics.tsv.gz https://datasets.imdbws.com/title.basics.tsv.gz
          wget -q -O ./data/title.ratings.tsv.gz https://datasets.imdbws.com/title.ratings.tsv.gz
      
      - name: Build Local IMDb Database
        run: python src/build_imdb_db.py

      - name: Process Reddit Data
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
        run: python src/process_reddit.py

      - name: Commit and Push Database
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions-bot@github.com'
          git add -f recommendations.db
          # Only commit if there are changes
          git diff --staged --quiet || git commit -m "Update recommendations database"
          git push

  # ===================================================================
  # JOB 2: Build and push the Docker image to Docker Hub
  # ===================================================================
  build-and-push-docker:
    # This job will only start AFTER 'build-data' has succeeded
    needs: build-data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # This checkout gets the code AND the freshly updated recommendations.db
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/stremio-vibe-addon:latest 
          # Example: if your username is 'foobar', the image will be 'foobar/stremio-vibe-addon:latest'
