name: Process Data and Publish to GHCR

on:
  schedule:
    - cron: '0 5 * * *' # Runs every day at 5 AM UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # ===================================================================
  # JOB 1: Process Reddit data and update the recommendations database
  # ===================================================================
  build-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ... (This entire job remains exactly the same as before) ...

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Create data directory
        run: mkdir -p ./data
      - name: Cache and Download IMDb Datasets
        uses: actions/cache@v4
        id: cache-imdb
        with:
          path: ./data/*.tsv.gz
          key: ${{ runner.os }}-imdb-data-v1
      - name: Download IMDb Datasets if not cached
        if: steps.cache-imdb.outputs.cache-hit != 'true'
        run: |
          echo "Cache not found, downloading IMDb data..."
          wget -q -O ./data/title.basics.tsv.gz https://datasets.imdbws.com/title.basics.tsv.gz
          wget -q -O ./data/title.ratings.tsv.gz https://datasets.imdbws.com/title.ratings.tsv.gz
      - name: Build Local IMDb Database
        run: python src/build_imdb_db.py
      - name: Process Reddit Data
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
        run: python src/process_reddit.py
      - name: Commit and Push Database
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions-bot@github.com'
          git add -f recommendations.db
          git diff --staged --quiet || git commit -m "Update recommendations database"
          git push

  # ===================================================================
  # JOB 2: Build and push the Docker image to GitHub Container Registry
  # ===================================================================
  build-and-push-docker:
    needs: build-data
    runs-on: ubuntu-latest
    # --- CHANGED: Added permissions to write to GitHub Packages ---
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # --- CHANGED: This step now logs into GHCR using the GITHUB_TOKEN ---
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --- CHANGED: This step now builds and pushes to GHCR with a new tag format ---
      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/stremio-vibe-addon:latest
          # This creates a tag like: ghcr.io/your-github-username/your-repo-name:latest
